services:
  bookkeeping-web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: bin/rails s -b 0.0.0.0
    entrypoint: /usr/bin/entrypoint.sh
    stdin_open: true
    tty: true
    volumes:
      - .:/bookke
    depends_on:
      - db
    deploy:
      replicas: 2
    restart: always
    networks: 
      - nginx-ingress
      - bookke_net

  db:
    image: postgres:11
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg_pass
    restart: always
    mem_limit: 512M
    networks: 
      - bookke_net

volumes:
  postgres:

networks:
  nginx-ingress:
    name: nginx-ingress
    external: true
  bookke_net:
    name: bookke_net
