services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_alpine
      platforms:
        - linux/amd64
    command: bin/rails s -b 0.0.0.0
    entrypoint: /usr/bin/entrypoint.sh
    stdin_open: true
    tty: true
    volumes:
      - .:/bookke
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:11
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg_pass

volumes:
  postgres: